app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


fos_user_registration_confirmed:
    pattern: /registration/confirmed
    defaults: { _controller: AppBundle:AfterHours:confirmed }
    requirements:
        _method: GET